export enum ConfigVar {
  HOST = 'HOST',
  PORT = 'PORT',

  // Database
  MONGO_URI = 'MONGO_URI',

  // JWT
  JWT_SECRET = 'JWT_SECRET',
  JWT_EXPIRES_IN = 'JWT_EXPIRES_IN',
  JWT_REFRESH_SECRET = 'JWT_REFRESH_SECRET',
  JWT_REFRESH_EXPIRES_IN = 'JWT_REFRESH_EXPIRES_IN',
}
